[theme]
base = "dark"
primaryColor = "#00dcff"
backgroundColor = "#080b12"
secondaryBackgroundColor = "#0d1117"
textColor = "#e6edf3"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
